/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SplashScreen;

import AirTicketing.AirTicket;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class SplashScreen extends javax.swing.JFrame {

    //Variables to store username and password
     public String username,password;
    
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        //Setting Labels Invisible for all Login Options
        invisibilityLogins();
    }

    public void invisibilityLogins(){
      //Setting Labels Invisible for all Login Options
        splashLoginLbl.setVisible(false);
        usernameLbl.setVisible(false);
        passwordLbl.setVisible(false);
        splashUsernameField.setVisible(false);
        splashPasswordField.setVisible(false);
        loginBtn.setVisible(false);
    }
    public void visibilityLogins(){
        /**Setting Labels Visible for all Login Options
         * Also Setting progressBar and %Label Invisible
         */
        splashLoginLbl.setVisible(true);
        usernameLbl.setVisible(true);
        passwordLbl.setVisible(true);
        splashUsernameField.setVisible(true);
        splashPasswordField.setVisible(true);
        loginBtn.setVisible(true);
        progressBar.setVisible(false);
        lblLoadingSplash.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashScreenPanel = new javax.swing.JPanel();
        lblSplashAirTicketing = new javax.swing.JLabel();
        lblSplashAirTicketing1 = new javax.swing.JLabel();
        lblLoadingSplash = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        splashLoginLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        splashUsernameField = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        splashExitBtn = new javax.swing.JButton();
        splashPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        splashScreenPanel.setBackground(new java.awt.Color(51, 255, 204));
        splashScreenPanel.setLayout(null);

        lblSplashAirTicketing.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblSplashAirTicketing.setForeground(new java.awt.Color(51, 51, 255));
        lblSplashAirTicketing.setText("Welcome To ");
        splashScreenPanel.add(lblSplashAirTicketing);
        lblSplashAirTicketing.setBounds(270, 40, 160, 55);

        lblSplashAirTicketing1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblSplashAirTicketing1.setForeground(new java.awt.Color(51, 51, 255));
        lblSplashAirTicketing1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSplashAirTicketing1.setText("Air Ticketing");
        splashScreenPanel.add(lblSplashAirTicketing1);
        lblSplashAirTicketing1.setBounds(230, 100, 221, 40);

        lblLoadingSplash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoadingSplash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoadingSplash.setText("0%");
        splashScreenPanel.add(lblLoadingSplash);
        lblLoadingSplash.setBounds(310, 160, 63, 27);
        lblLoadingSplash.getAccessibleContext().setAccessibleName("");

        progressBar.setForeground(new java.awt.Color(51, 51, 51));
        splashScreenPanel.add(progressBar);
        progressBar.setBounds(190, 210, 303, 33);

        splashLoginLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        splashLoginLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        splashLoginLbl.setText("Login Form");
        splashScreenPanel.add(splashLoginLbl);
        splashLoginLbl.setBounds(260, 180, 150, 30);

        usernameLbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        usernameLbl.setText("Username");
        splashScreenPanel.add(usernameLbl);
        usernameLbl.setBounds(250, 250, 70, 20);

        splashUsernameField.setToolTipText("Type Username Here");
        splashScreenPanel.add(splashUsernameField);
        splashUsernameField.setBounds(370, 250, 130, 19);

        passwordLbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        passwordLbl.setText("Password");
        splashScreenPanel.add(passwordLbl);
        passwordLbl.setBounds(250, 280, 60, 20);

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        splashScreenPanel.add(loginBtn);
        loginBtn.setBounds(300, 330, 90, 30);

        splashExitBtn.setBackground(new java.awt.Color(153, 153, 153));
        splashExitBtn.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        splashExitBtn.setForeground(new java.awt.Color(255, 0, 0));
        splashExitBtn.setText("X");
        splashExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splashExitBtnActionPerformed(evt);
            }
        });
        splashScreenPanel.add(splashExitBtn);
        splashExitBtn.setBounds(640, 0, 60, 40);
        splashScreenPanel.add(splashPasswordField);
        splashPasswordField.setBounds(370, 280, 130, 19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashScreenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashScreenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(701, 393));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:        
        //Checking for empty fields
        if(splashUsernameField.getText().equals("") || splashPasswordField.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Empty Fields","Error" , JOptionPane.ERROR_MESSAGE);            
        }else if(splashPasswordField.getText().length()<6 || splashPasswordField.getText().length()>=10){
            JOptionPane.showMessageDialog(rootPane, "Password should be 6-10 characters", "Message", JOptionPane.INFORMATION_MESSAGE);
        }else{          
           username=splashUsernameField.getText();
           password=splashPasswordField.getText();   
           AirTicket Ticket=new AirTicket(username); //New Instance of AirTicket class              
           Ticket.setVisible(true);  //Setting the AirTicket class Visible
           
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

 
    private void splashExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splashExitBtnActionPerformed
        // TODO add your handling code here:
        //closing the app
        System.exit(0);
    }//GEN-LAST:event_splashExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblLoadingSplash;
    private javax.swing.JLabel lblSplashAirTicketing;
    private javax.swing.JLabel lblSplashAirTicketing1;
    public javax.swing.JButton loginBtn;
    private javax.swing.JLabel passwordLbl;
    public javax.swing.JProgressBar progressBar;
    private javax.swing.JButton splashExitBtn;
    private javax.swing.JLabel splashLoginLbl;
    private javax.swing.JPasswordField splashPasswordField;
    private javax.swing.JPanel splashScreenPanel;
    public javax.swing.JTextField splashUsernameField;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables
}
